// Country data based on where stripe is available

export const countries = [
    { "name": "Australia", "code": "AU", "currency": "AUD" },
    { "name": "Austria", "code": "AT", "currency": "EUR" },
    { "name": "Belgium", "code": "BE", "currency": "EUR" },
    { "name": "Brazil", "code": "BR", "currency": "BRL" },
    { "name": "Bulgaria", "code": "BG", "currency": "BGN" },
    { "name": "Canada", "code": "CA", "currency": "CAD" },
    { "name": "Croatia", "code": "HR", "currency": "EUR" },
    { "name": "Cyprus", "code": "CY", "currency": "EUR" },
    { "name": "Czech Republic", "code": "CZ", "currency": "CZK" },
    { "name": "Denmark", "code": "DK", "currency": "DKK" },
    { "name": "Estonia", "code": "EE", "currency": "EUR" },
    { "name": "Finland", "code": "FI", "currency": "EUR" },
    { "name": "France", "code": "FR", "currency": "EUR" },
    { "name": "Germany", "code": "DE", "currency": "EUR" },
    { "name": "Ghana", "code": "GH", "currency": "GHS" },
    { "name": "Gibraltar", "code": "GI", "currency": "GIP" },
    { "name": "Greece", "code": "GR", "currency": "EUR" },
    { "name": "Hong Kong", "code": "HK", "currency": "HKD" },
    { "name": "Hungary", "code": "HU", "currency": "HUF" },
    { "name": "India", "code": "IN", "currency": "INR" },
    { "name": "Indonesia", "code": "ID", "currency": "IDR" },
    { "name": "Ireland", "code": "IE", "currency": "EUR" },
    { "name": "Italy", "code": "IT", "currency": "EUR" },
    { "name": "Japan", "code": "JP", "currency": "JPY" },
    { "name": "Kenya", "code": "KE", "currency": "KES" },
    { "name": "Latvia", "code": "LV", "currency": "EUR" },
    { "name": "Liechtenstein", "code": "LI", "currency": "CHF" },
    { "name": "Lithuania", "code": "LT", "currency": "EUR" },
    { "name": "Luxembourg", "code": "LU", "currency": "EUR" },
    { "name": "Malaysia", "code": "MY", "currency": "MYR" },
    { "name": "Malta", "code": "MT", "currency": "EUR" },
    { "name": "Mexico", "code": "MX", "currency": "MXN" },
    { "name": "Netherlands", "code": "NL", "currency": "EUR" },
    { "name": "New Zealand", "code": "NZ", "currency": "NZD" },
    { "name": "Nigeria", "code": "NG", "currency": "NGN" },
    { "name": "Norway", "code": "NO", "currency": "NOK" },
    { "name": "Poland", "code": "PL", "currency": "PLN" },
    { "name": "Portugal", "code": "PT", "currency": "EUR" },
    { "name": "Romania", "code": "RO", "currency": "RON" },
    { "name": "Singapore", "code": "SG", "currency": "SGD" },
    { "name": "Slovakia", "code": "SK", "currency": "EUR" },
    { "name": "Slovenia", "code": "SI", "currency": "EUR" },
    { "name": "South Africa", "code": "ZA", "currency": "ZAR" },
    { "name": "Spain", "code": "ES", "currency": "EUR" },
    { "name": "Sweden", "code": "SE", "currency": "SEK" },
    { "name": "Switzerland", "code": "CH", "currency": "CHF" },
    { "name": "Thailand", "code": "TH", "currency": "THB" },
    { "name": "United Arab Emirates", "code": "AE", "currency": "AED" },
    { "name": "United Kingdom", "code": "GB", "currency": "GBP" },
    { "name": "United States", "code": "US", "currency": "USD" }
];
